language: c

before_install: sudo apt update

install: sudo apt install build-essential devscripts debhelper dh-autoreconf libglib2.0-dev systemd

script: skip

after_script: dpkg-buildpackage -us -uc -b
